-- GERADO por scripts/import-competencias.mjs a partir de
-- docs/Competencia_das_Camaras_TJPR_1.xlsx. Não edite à mão: rode o script de novo.
--
-- Idempotente: reaplicar depois de uma nova emenda regimental substitui o conteúdo inteiro, em vez
-- de acumular duas versões da competência — o dado é a norma vigente, não um histórico.
begin;

delete from camara_competencias;

insert into camara_competencias
  (area, grupo, camaras, secao, item, competencia, descricao, ordem, fonte)
values
  ('CIVEL', '1ª, 2ª e 3ª Cíveis', array['1ª Câmara Cível', '2ª Câmara Cível', '3ª Câmara Cível'], '1ª Seção Cível', 'a', 'tributário', 'Trata de ações envolvendo tributos, impostos, taxas e contribuições, como execuções fiscais, ações anulatórias de débito tributário e mandados de segurança em matéria tributária.', 1, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '1ª, 2ª e 3ª Cíveis', array['1ª Câmara Cível', '2ª Câmara Cível', '3ª Câmara Cível'], '1ª Seção Cível', 'b', 'responsabilidade civil em que for parte pessoa jurídica de direito público e entidades paraestatais', 'Abrange pedidos de indenização por danos materiais ou morais quando o Estado, autarquias, fundações públicas ou entidades paraestatais (empresas públicas e sociedades de economia mista) figuram como parte.', 2, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '1ª, 2ª e 3ª Cíveis', array['1ª Câmara Cível', '2ª Câmara Cível', '3ª Câmara Cível'], '1ª Seção Cível', 'c', 'servidores públicos, exceto matéria previdenciária', 'Compreende questões funcionais de servidores públicos — remuneração, promoção, punições disciplinares, reintegração ao cargo — excluindo-se temas de aposentadoria e benefícios previdenciários.', 3, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '1ª, 2ª e 3ª Cíveis', array['1ª Câmara Cível', '2ª Câmara Cível', '3ª Câmara Cível'], '1ª Seção Cível', 'd', 'alienação fiduciária e alheios', 'Engloba ações sobre bens móveis ou imóveis dados em garantia fiduciária (como busca e apreensão de veículos financiados) e demais matérias residuais atribuídas a esta câmara.', 4, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'a', 'ação popular, exceto tributário, previdência pública e privada e ensino', 'Ações movidas por qualquer cidadão para anular atos lesivos ao patrimônio público, à moralidade administrativa, ao meio ambiente ou ao patrimônio histórico e cultural, exceto quando envolvem matéria tributária, previdência pública/privada ou ensino.', 1, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'b', 'improbidade administrativa', 'Processos que apuram atos de improbidade cometidos por agentes públicos — enriquecimento ilícito, prejuízo ao erário, violação de princípios da administração pública — com possíveis sanções de perda de bens, multa e suspensão de direitos políticos.', 2, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'c', 'ação civil pública, exceto matéria tributária, previdência pública e privada e ensino, observando-se, quanto às coletivas, a distribuição às Câmaras Cíveis de acordo com a matéria de sua especialização', 'Ações civis públicas propostas em defesa de interesses difusos e coletivos (consumidor, patrimônio público, ordem urbanística etc.), exceto matéria tributária, previdenciária e de ensino; nas ações coletivas, a distribuição observa a especialização de cada Câmara Cível.', 3, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'd', 'ações e execuções de penalidades administrativas que não possuam natureza tributária', 'Cobrança judicial e discussão sobre a validade de multas e sanções aplicadas pela administração pública que não tenham natureza tributária, como penalidades por infrações sanitárias ou ambientais.', 4, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'e', 'licitação e contratos administrativos', 'Disputas sobre processos licitatórios e sobre a execução, revisão ou rescisão de contratos firmados com a administração pública.', 5, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'g', 'concursos públicos', 'Questões relacionadas a concursos públicos, como nomeação, convocação, eliminação de candidatos e validade de editais.', 6, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'h', 'mandados de segurança e de injunção, ressalvada outra especialização', 'Ações constitucionais que buscam proteger direito líquido e certo violado por autoridade pública (mandado de segurança) ou suprir omissão legislativa que impeça o exercício de um direito (mandado de injunção), quando não atribuídos a outra câmara especializada.', 7, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'i', 'intervenção estadual nos Municípios', 'Processos relativos à intervenção do Estado em Municípios, medida excepcional destinada a restabelecer a normalidade institucional, financeira ou administrativa municipal.', 8, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'j', 'proteção do meio ambiente, exceto as que digam respeito a responsabilidade civil', 'Ações voltadas à tutela do meio ambiente — interdição de atividades poluidoras, obrigações de recuperação ambiental — exceto quando o pedido principal é de indenização por responsabilidade civil.', 9, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'k', 'residual público', 'Demais matérias de direito público que não se enquadrem nas competências específicas de outra câmara.', 10, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'l', 'greve dos servidores públicos', 'Ações relacionadas ao exercício do direito de greve por servidores públicos, incluindo a declaração de abusividade do movimento e questões de desconto salarial.', 11, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'm', 'servidores públicos em geral, exceto matéria previdenciária', 'Litígios funcionais de servidores públicos em geral — remuneração, cargos, sanções — exceto matéria previdenciária.', 12, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'n', 'prestação de serviços públicos de fornecimento de energia elétrica, água e gás, exceto quando concernente exclusivamente a responsabilidade civil', 'Questões sobre fornecimento, corte e cobrança de serviços públicos essenciais como energia elétrica, água e gás, exceto quando o pedido é exclusivamente de indenização por responsabilidade civil.', 13, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '4ª e 5ª Cíveis', array['4ª Câmara Cível', '5ª Câmara Cível'], '2ª Seção Cível', 'o', 'alienação fiduciária e alheios', 'Bens em garantia fiduciária e demais casos residuais desta câmara.', 14, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '6ª e 7ª Cíveis', array['6ª Câmara Cível', '7ª Câmara Cível'], '3ª Seção Cível', 'a', 'previdência pública e privada', 'Benefícios previdenciários do regime geral (INSS) e de planos de previdência privada/complementar, como aposentadorias, pensões e auxílios.', 1, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '6ª e 7ª Cíveis', array['6ª Câmara Cível', '7ª Câmara Cível'], '3ª Seção Cível', 'b', 'ensino', 'Questões envolvendo instituições de ensino, contratos educacionais, mensalidades escolares e matrícula.', 2, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '6ª e 7ª Cíveis', array['6ª Câmara Cível', '7ª Câmara Cível'], '3ª Seção Cível', 'c', 'prestação de serviço ao usuário final de telefonia fixa, telefonia móvel, internet e tv por assinatura e os demais contratos de prestação de serviços, regulados pelos artigos 593 a 609 do Código Civil, excluídos os de competência da 4ª e 5ª Câmaras Cíveis e os concernentes exclusivamente a responsabilidade civil', 'Contratos de telefonia fixa e móvel, internet e TV por assinatura, além de outros contratos de prestação de serviços regulados pelos artigos 593 a 609 do Código Civil, excluídos os de competência da 4ª e 5ª Câmaras Cíveis e os casos de mera responsabilidade civil.', 3, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '6ª e 7ª Cíveis', array['6ª Câmara Cível', '7ª Câmara Cível'], '3ª Seção Cível', 'd', 'alienação fiduciária e alheios', 'Bens em garantia fiduciária e demais casos residuais desta câmara.', 4, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '8ª, 9ª e 10ª Cíveis', array['8ª Câmara Cível', '9ª Câmara Cível', '10ª Câmara Cível'], '4ª Seção Cível', 'a', 'responsabilidade civil, inclusive as decorrentes de acidente de veículo e de acidente de trabalho, exceto entes públicos', 'Ações de indenização por danos materiais e morais em geral, incluindo acidentes de trânsito e acidentes de trabalho, exceto quando o réu é ente público.', 1, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '8ª, 9ª e 10ª Cíveis', array['8ª Câmara Cível', '9ª Câmara Cível', '10ª Câmara Cível'], '4ª Seção Cível', 'b', 'condomínio em edifício', 'Conflitos entre condôminos e entre condomínio e condômino, como cobrança de taxas condominiais e questões de convenção de condomínio.', 2, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '8ª, 9ª e 10ª Cíveis', array['8ª Câmara Cível', '9ª Câmara Cível', '10ª Câmara Cível'], '4ª Seção Cível', 'c', 'ações e execuções de contrato de seguro e de plano de saúde', 'Ações e execuções relativas a contratos de seguro (veículo, vida, residencial) e de planos de saúde, incluindo negativa de cobertura.', 3, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '8ª, 9ª e 10ª Cíveis', array['8ª Câmara Cível', '9ª Câmara Cível', '10ª Câmara Cível'], '4ª Seção Cível', 'd', 'alienação fiduciária e alheios', 'Bens em garantia fiduciária e demais casos residuais desta câmara.', 4, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '11ª e 12ª Cíveis', array['11ª Câmara Cível', '12ª Câmara Cível'], '5ª Seção Cível', 'a', 'Direito de Família, união estável e homoafetiva', 'Divórcio, separação, guarda e regulamentação de visitas, pensão alimentícia, união estável e uniões homoafetivas.', 1, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '11ª e 12ª Cíveis', array['11ª Câmara Cível', '12ª Câmara Cível'], '5ª Seção Cível', 'b', 'ECA, ressalvada a matéria infracional', 'Questões cíveis previstas no Estatuto da Criança e do Adolescente, como adoção, guarda e destituição do poder familiar, excluída a matéria infracional.', 2, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '11ª e 12ª Cíveis', array['11ª Câmara Cível', '12ª Câmara Cível'], '5ª Seção Cível', 'c', 'Direito das Sucessões', 'Inventários, arrolamentos, partilhas de bens e demais questões relacionadas à sucessão hereditária.', 3, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '11ª e 12ª Cíveis', array['11ª Câmara Cível', '12ª Câmara Cível'], '5ª Seção Cível', 'd', 'alienação fiduciária e alheios', 'Bens em garantia fiduciária e demais casos residuais desta câmara.', 4, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '13ª, 14ª, 15ª e 16ª Cíveis', array['13ª Câmara Cível', '14ª Câmara Cível', '15ª Câmara Cível', '16ª Câmara Cível'], '6ª Seção Cível', 'a', 'execuções de título extrajudicial e suas ações, inclusive quando cumuladas com pedido de indenização', 'Ações de execução fundadas em títulos extrajudiciais (notas promissórias, cheques, contratos etc.), inclusive quando cumuladas com pedido de indenização.', 1, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '13ª, 14ª, 15ª e 16ª Cíveis', array['13ª Câmara Cível', '14ª Câmara Cível', '15ª Câmara Cível', '16ª Câmara Cível'], '6ª Seção Cível', 'b', 'negócios jurídicos bancários e cartões de crédito, inclusive quando cumuladas com pedido de indenização, exceto arrendamento mercantil', 'Contratos bancários em geral e de cartão de crédito, incluindo revisão de cláusulas e cobrança de dívidas, mesmo quando cumulados com pedido de indenização, exceto arrendamento mercantil.', 2, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '13ª, 14ª, 15ª e 16ª Cíveis', array['13ª Câmara Cível', '14ª Câmara Cível', '15ª Câmara Cível', '16ª Câmara Cível'], '6ª Seção Cível', 'c', 'alienação fiduciária e alheios', 'Bens em garantia fiduciária e demais casos residuais desta câmara.', 3, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '17ª e 18ª Cíveis', array['17ª Câmara Cível', '18ª Câmara Cível'], '7ª Seção Cível', 'a', 'domínio e posse pura, exceto quando decorrentes de resolução e nulidade de negócios jurídicos', 'Ações possessórias (reintegração e manutenção de posse) e de reconhecimento de domínio, exceto quando decorrem de resolução ou nulidade de negócio jurídico.', 1, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '17ª e 18ª Cíveis', array['17ª Câmara Cível', '18ª Câmara Cível'], '7ª Seção Cível', 'b', 'Direito Falimentar, exceto matéria penal', 'Processos de falência e de recuperação judicial e extrajudicial de empresas, exceto os crimes falimentares.', 2, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '17ª e 18ª Cíveis', array['17ª Câmara Cível', '18ª Câmara Cível'], '7ª Seção Cível', 'c', 'dissolução e liquidação de sociedade', 'Ações de dissolução parcial ou total de sociedades empresárias e sua liquidação.', 3, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '17ª e 18ª Cíveis', array['17ª Câmara Cível', '18ª Câmara Cível'], '7ª Seção Cível', 'd', 'arrendamento mercantil', 'Contratos de leasing (arrendamento mercantil) de bens móveis ou imóveis.', 4, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '17ª e 18ª Cíveis', array['17ª Câmara Cível', '18ª Câmara Cível'], '7ª Seção Cível', 'e', 'contratos de consórcio de bem móvel ou imóvel', 'Litígios envolvendo contratos de consórcio para aquisição de bens móveis ou imóveis, como contemplação, atraso na entrega e exclusão de consorciado.', 5, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '17ª e 18ª Cíveis', array['17ª Câmara Cível', '18ª Câmara Cível'], '7ª Seção Cível', 'f', 'Registros Públicos', 'Procedimentos de dúvida e retificação em registros públicos, como registro de imóveis e registro civil.', 6, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '17ª e 18ª Cíveis', array['17ª Câmara Cível', '18ª Câmara Cível'], '7ª Seção Cível', 'g', 'arrendamento rural, parceria agrícola e empreitada', 'Contratos agrários de arrendamento rural e parceria agrícola, além de contratos de empreitada.', 7, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '17ª e 18ª Cíveis', array['17ª Câmara Cível', '18ª Câmara Cível'], '7ª Seção Cível', 'h', 'locação, inclusive suas execuções', 'Contratos de locação residencial e comercial, incluindo ações de despejo, revisional de aluguel e execução de valores locatícios.', 8, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '17ª e 18ª Cíveis', array['17ª Câmara Cível', '18ª Câmara Cível'], '7ª Seção Cível', 'i', 'alienação fiduciária e alheios', 'Bens em garantia fiduciária e demais casos residuais desta câmara.', 9, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '19ª e 20ª Cíveis', array['19ª Câmara Cível', '20ª Câmara Cível'], '8ª Seção Cível', 'a', 'compromisso e/ou contrato de compra e venda de bens imóveis, sua revisão, resolução, resilição ou rescisão, inclusive referente a vício ou fato do produto, cumulada ou não com responsabilidade indenizatória', 'Contratos de compra e venda de imóveis, incluindo revisão, resolução, resilição ou rescisão, e vícios do imóvel (vício redibitório), cumulados ou não com pedido de indenização.', 1, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '19ª e 20ª Cíveis', array['19ª Câmara Cível', '20ª Câmara Cível'], '8ª Seção Cível', 'b', 'adjudicação compulsória e obrigação de fazer consistente na outorga de escritura pública definitiva, cumulada ou não com indenizatória', 'Ações que buscam obrigar o vendedor a outorgar a escritura pública definitiva do imóvel, cumuladas ou não com pedido de indenização.', 2, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '19ª e 20ª Cíveis', array['19ª Câmara Cível', '20ª Câmara Cível'], '8ª Seção Cível', 'c', 'ação monitória em geral, ressalvada a competência específica das demais câmaras relativamente ao negócio jurídico subjacente', 'Ações monitórias para cobrança de dívida com prova escrita sem força executiva, ressalvada a competência específica de outra câmara conforme o negócio jurídico subjacente.', 3, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CIVEL', '19ª e 20ª Cíveis', array['19ª Câmara Cível', '20ª Câmara Cível'], '8ª Seção Cível', 'd', 'alienação fiduciária e alheios', 'Bens em garantia fiduciária e demais casos residuais desta câmara.', 4, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '1ª Criminal', array['1ª Câmara Criminal'], 'Seção Criminal', 'a', 'crimes contra a pessoa, exceto os contra a honra', 'Homicídio, lesão corporal e demais crimes contra a vida e a integridade física, exceto os crimes contra a honra (calúnia, difamação e injúria).', 1, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '1ª Criminal', array['1ª Câmara Criminal'], 'Seção Criminal', 'b', 'crimes militares', 'Crimes de natureza militar, praticados por militares ou contra instituições militares.', 2, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '1ª Criminal', array['1ª Câmara Criminal'], 'Seção Criminal', 'c', 'processos oriundos do Conselho de Justificação da Polícia Militar', 'Processos originados do Conselho de Justificação da Polícia Militar, que apura a incapacidade do militar para permanecer na corporação.', 3, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '2ª Criminal', array['2ª Câmara Criminal'], 'Seção Criminal', 'a', 'infrações penais atribuídas a Prefeitos Municipais', 'Crimes de responsabilidade e demais infrações penais atribuídas a Prefeitos Municipais no exercício do cargo.', 1, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '2ª Criminal', array['2ª Câmara Criminal'], 'Seção Criminal', 'b', 'crimes contra a administração pública', 'Corrupção, peculato, prevaricação e demais crimes praticados por funcionários públicos contra a administração.', 2, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '2ª Criminal', array['2ª Câmara Criminal'], 'Seção Criminal', 'c', 'crimes contra a fé pública', 'Falsificação de documentos públicos ou particulares, moeda falsa e demais crimes que atentam contra a fé pública.', 3, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '2ª Criminal', array['2ª Câmara Criminal'], 'Seção Criminal', 'd', 'crimes contra a honra', 'Calúnia, difamação e injúria.', 4, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '2ª Criminal', array['2ª Câmara Criminal'], 'Seção Criminal', 'e', 'crimes contra a incolumidade pública, incluídos os definidos no Estatuto do Desarmamento', 'Crimes que colocam em risco a segurança coletiva, como explosão e incêndio, incluindo os definidos no Estatuto do Desarmamento (posse e porte ilegal de arma de fogo).', 5, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '2ª Criminal', array['2ª Câmara Criminal'], 'Seção Criminal', 'f', 'crimes contra a ordem tributária e econômica, contra as relações de consumo e falimentares', 'Sonegação fiscal, crimes contra o sistema financeiro e a ordem econômica, crimes contra as relações de consumo e crimes falimentares.', 6, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '2ª Criminal', array['2ª Câmara Criminal'], 'Seção Criminal', 'g', 'crimes ambientais', 'Crimes praticados contra o meio ambiente, como poluição e desmatamento ilegal.', 7, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '2ª Criminal', array['2ª Câmara Criminal'], 'Seção Criminal', 'h', 'demais infrações penais', 'Demais infrações penais não atribuídas especificamente a outra câmara criminal.', 8, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '2ª Criminal', array['2ª Câmara Criminal'], 'Seção Criminal', 'i', 'atos infracionais previstos no Estatuto da Criança e do Adolescente, por estes praticados', 'Atos infracionais (equivalentes a crimes) cometidos por adolescentes, apurados nos termos do Estatuto da Criança e do Adolescente.', 9, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '3ª, 4ª e 5ª Criminais', array['3ª Câmara Criminal', '4ª Câmara Criminal', '5ª Câmara Criminal'], 'Seção Criminal', 'a', 'crimes contra o patrimônio', 'Furto, roubo, estelionato, apropriação indébita e demais crimes contra o patrimônio.', 1, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '3ª, 4ª e 5ª Criminais', array['3ª Câmara Criminal', '4ª Câmara Criminal', '5ª Câmara Criminal'], 'Seção Criminal', 'b', 'crimes contra a dignidade sexual', 'Estupro e demais crimes contra a dignidade sexual.', 2, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '3ª, 4ª e 5ª Criminais', array['3ª Câmara Criminal', '4ª Câmara Criminal', '5ª Câmara Criminal'], 'Seção Criminal', 'c', 'crimes contra a paz pública', 'Crimes contra a paz pública, como associação criminosa e organização criminosa.', 3, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '3ª, 4ª e 5ª Criminais', array['3ª Câmara Criminal', '4ª Câmara Criminal', '5ª Câmara Criminal'], 'Seção Criminal', 'd', 'infrações penais relativas a tóxicos e entorpecentes', 'Tráfico, posse e demais infrações relacionadas a drogas, previstas na Lei de Drogas.', 4, 'Emenda Regimental nº 17, de 21 de setembro de 2022'),
  ('CRIMINAL', '3ª, 4ª e 5ª Criminais', array['3ª Câmara Criminal', '4ª Câmara Criminal', '5ª Câmara Criminal'], 'Seção Criminal', 'e', 'demais infrações penais', 'Demais infrações penais não atribuídas especificamente a outra câmara criminal.', 5, 'Emenda Regimental nº 17, de 21 de setembro de 2022');

commit;
