// GERADO por scripts/import-competencias.mjs a partir de
// docs/Competencia_das_Camaras_TJPR_1.xlsx. Não edite à mão: rode o script de novo.
//
// Este arquivo é a cópia em memória da tabela `camara_competencias`. Ele existe para que a
// consulta de competência funcione sem banco e sem rede, como o resto do modo fixture
// (critério de aceite 16) — o seed SQL gerado no mesmo passo é a cópia do Postgres.
import type { CamaraCompetencia } from "../schemas/competencia.schema";

/** Norma vigente que a planilha reproduz. Toda linha abaixo vem dela. */
export const FONTE = "Emenda Regimental nº 17, de 21 de setembro de 2022";

/**
 * Ressalva do próprio documento de origem, reproduzida porque muda como o dado pode ser usado:
 * o item "e)" da 4ª e 5ª Câmaras Cíveis está duplicado e a letra "f)" não consta — reprodução fiel do documento original do TJPR.
 * As descrições da coluna "Descrição" são um resumo explicativo em linguagem mais acessível, elaborado a partir do texto oficial, sem valor normativo — o texto que vale juridicamente é sempre o da coluna "Competências".
 * Atualizada até a Emenda Regimental nº 17, de 21 de setembro de 2022.
 */
export const NOTA_FONTE = "o item \"e)\" da 4ª e 5ª Câmaras Cíveis está duplicado e a letra \"f)\" não consta — reprodução fiel do documento original do TJPR. As descrições da coluna \"Descrição\" são um resumo explicativo em linguagem mais acessível, elaborado a partir do texto oficial, sem valor normativo — o texto que vale juridicamente é sempre o da coluna \"Competências\". Atualizada até a Emenda Regimental nº 17, de 21 de setembro de 2022.";

export const CAMARA_COMPETENCIAS: readonly CamaraCompetencia[] = [
  {
    area: "CIVEL",
    grupo: "1ª, 2ª e 3ª Cíveis",
    camaras: ["1ª Câmara Cível", "2ª Câmara Cível", "3ª Câmara Cível"],
    secao: "1ª Seção Cível",
    item: "a",
    competencia: "tributário",
    descricao: "Trata de ações envolvendo tributos, impostos, taxas e contribuições, como execuções fiscais, ações anulatórias de débito tributário e mandados de segurança em matéria tributária.",
    ordem: 1,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "1ª, 2ª e 3ª Cíveis",
    camaras: ["1ª Câmara Cível", "2ª Câmara Cível", "3ª Câmara Cível"],
    secao: "1ª Seção Cível",
    item: "b",
    competencia: "responsabilidade civil em que for parte pessoa jurídica de direito público e entidades paraestatais",
    descricao: "Abrange pedidos de indenização por danos materiais ou morais quando o Estado, autarquias, fundações públicas ou entidades paraestatais (empresas públicas e sociedades de economia mista) figuram como parte.",
    ordem: 2,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "1ª, 2ª e 3ª Cíveis",
    camaras: ["1ª Câmara Cível", "2ª Câmara Cível", "3ª Câmara Cível"],
    secao: "1ª Seção Cível",
    item: "c",
    competencia: "servidores públicos, exceto matéria previdenciária",
    descricao: "Compreende questões funcionais de servidores públicos — remuneração, promoção, punições disciplinares, reintegração ao cargo — excluindo-se temas de aposentadoria e benefícios previdenciários.",
    ordem: 3,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "1ª, 2ª e 3ª Cíveis",
    camaras: ["1ª Câmara Cível", "2ª Câmara Cível", "3ª Câmara Cível"],
    secao: "1ª Seção Cível",
    item: "d",
    competencia: "alienação fiduciária e alheios",
    descricao: "Engloba ações sobre bens móveis ou imóveis dados em garantia fiduciária (como busca e apreensão de veículos financiados) e demais matérias residuais atribuídas a esta câmara.",
    ordem: 4,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "a",
    competencia: "ação popular, exceto tributário, previdência pública e privada e ensino",
    descricao: "Ações movidas por qualquer cidadão para anular atos lesivos ao patrimônio público, à moralidade administrativa, ao meio ambiente ou ao patrimônio histórico e cultural, exceto quando envolvem matéria tributária, previdência pública/privada ou ensino.",
    ordem: 1,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "b",
    competencia: "improbidade administrativa",
    descricao: "Processos que apuram atos de improbidade cometidos por agentes públicos — enriquecimento ilícito, prejuízo ao erário, violação de princípios da administração pública — com possíveis sanções de perda de bens, multa e suspensão de direitos políticos.",
    ordem: 2,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "c",
    competencia: "ação civil pública, exceto matéria tributária, previdência pública e privada e ensino, observando-se, quanto às coletivas, a distribuição às Câmaras Cíveis de acordo com a matéria de sua especialização",
    descricao: "Ações civis públicas propostas em defesa de interesses difusos e coletivos (consumidor, patrimônio público, ordem urbanística etc.), exceto matéria tributária, previdenciária e de ensino; nas ações coletivas, a distribuição observa a especialização de cada Câmara Cível.",
    ordem: 3,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "d",
    competencia: "ações e execuções de penalidades administrativas que não possuam natureza tributária",
    descricao: "Cobrança judicial e discussão sobre a validade de multas e sanções aplicadas pela administração pública que não tenham natureza tributária, como penalidades por infrações sanitárias ou ambientais.",
    ordem: 4,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "e",
    competencia: "licitação e contratos administrativos",
    descricao: "Disputas sobre processos licitatórios e sobre a execução, revisão ou rescisão de contratos firmados com a administração pública.",
    ordem: 5,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "g",
    competencia: "concursos públicos",
    descricao: "Questões relacionadas a concursos públicos, como nomeação, convocação, eliminação de candidatos e validade de editais.",
    ordem: 6,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "h",
    competencia: "mandados de segurança e de injunção, ressalvada outra especialização",
    descricao: "Ações constitucionais que buscam proteger direito líquido e certo violado por autoridade pública (mandado de segurança) ou suprir omissão legislativa que impeça o exercício de um direito (mandado de injunção), quando não atribuídos a outra câmara especializada.",
    ordem: 7,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "i",
    competencia: "intervenção estadual nos Municípios",
    descricao: "Processos relativos à intervenção do Estado em Municípios, medida excepcional destinada a restabelecer a normalidade institucional, financeira ou administrativa municipal.",
    ordem: 8,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "j",
    competencia: "proteção do meio ambiente, exceto as que digam respeito a responsabilidade civil",
    descricao: "Ações voltadas à tutela do meio ambiente — interdição de atividades poluidoras, obrigações de recuperação ambiental — exceto quando o pedido principal é de indenização por responsabilidade civil.",
    ordem: 9,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "k",
    competencia: "residual público",
    descricao: "Demais matérias de direito público que não se enquadrem nas competências específicas de outra câmara.",
    ordem: 10,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "l",
    competencia: "greve dos servidores públicos",
    descricao: "Ações relacionadas ao exercício do direito de greve por servidores públicos, incluindo a declaração de abusividade do movimento e questões de desconto salarial.",
    ordem: 11,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "m",
    competencia: "servidores públicos em geral, exceto matéria previdenciária",
    descricao: "Litígios funcionais de servidores públicos em geral — remuneração, cargos, sanções — exceto matéria previdenciária.",
    ordem: 12,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "n",
    competencia: "prestação de serviços públicos de fornecimento de energia elétrica, água e gás, exceto quando concernente exclusivamente a responsabilidade civil",
    descricao: "Questões sobre fornecimento, corte e cobrança de serviços públicos essenciais como energia elétrica, água e gás, exceto quando o pedido é exclusivamente de indenização por responsabilidade civil.",
    ordem: 13,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "4ª e 5ª Cíveis",
    camaras: ["4ª Câmara Cível", "5ª Câmara Cível"],
    secao: "2ª Seção Cível",
    item: "o",
    competencia: "alienação fiduciária e alheios",
    descricao: "Bens em garantia fiduciária e demais casos residuais desta câmara.",
    ordem: 14,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "6ª e 7ª Cíveis",
    camaras: ["6ª Câmara Cível", "7ª Câmara Cível"],
    secao: "3ª Seção Cível",
    item: "a",
    competencia: "previdência pública e privada",
    descricao: "Benefícios previdenciários do regime geral (INSS) e de planos de previdência privada/complementar, como aposentadorias, pensões e auxílios.",
    ordem: 1,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "6ª e 7ª Cíveis",
    camaras: ["6ª Câmara Cível", "7ª Câmara Cível"],
    secao: "3ª Seção Cível",
    item: "b",
    competencia: "ensino",
    descricao: "Questões envolvendo instituições de ensino, contratos educacionais, mensalidades escolares e matrícula.",
    ordem: 2,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "6ª e 7ª Cíveis",
    camaras: ["6ª Câmara Cível", "7ª Câmara Cível"],
    secao: "3ª Seção Cível",
    item: "c",
    competencia: "prestação de serviço ao usuário final de telefonia fixa, telefonia móvel, internet e tv por assinatura e os demais contratos de prestação de serviços, regulados pelos artigos 593 a 609 do Código Civil, excluídos os de competência da 4ª e 5ª Câmaras Cíveis e os concernentes exclusivamente a responsabilidade civil",
    descricao: "Contratos de telefonia fixa e móvel, internet e TV por assinatura, além de outros contratos de prestação de serviços regulados pelos artigos 593 a 609 do Código Civil, excluídos os de competência da 4ª e 5ª Câmaras Cíveis e os casos de mera responsabilidade civil.",
    ordem: 3,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "6ª e 7ª Cíveis",
    camaras: ["6ª Câmara Cível", "7ª Câmara Cível"],
    secao: "3ª Seção Cível",
    item: "d",
    competencia: "alienação fiduciária e alheios",
    descricao: "Bens em garantia fiduciária e demais casos residuais desta câmara.",
    ordem: 4,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "8ª, 9ª e 10ª Cíveis",
    camaras: ["8ª Câmara Cível", "9ª Câmara Cível", "10ª Câmara Cível"],
    secao: "4ª Seção Cível",
    item: "a",
    competencia: "responsabilidade civil, inclusive as decorrentes de acidente de veículo e de acidente de trabalho, exceto entes públicos",
    descricao: "Ações de indenização por danos materiais e morais em geral, incluindo acidentes de trânsito e acidentes de trabalho, exceto quando o réu é ente público.",
    ordem: 1,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "8ª, 9ª e 10ª Cíveis",
    camaras: ["8ª Câmara Cível", "9ª Câmara Cível", "10ª Câmara Cível"],
    secao: "4ª Seção Cível",
    item: "b",
    competencia: "condomínio em edifício",
    descricao: "Conflitos entre condôminos e entre condomínio e condômino, como cobrança de taxas condominiais e questões de convenção de condomínio.",
    ordem: 2,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "8ª, 9ª e 10ª Cíveis",
    camaras: ["8ª Câmara Cível", "9ª Câmara Cível", "10ª Câmara Cível"],
    secao: "4ª Seção Cível",
    item: "c",
    competencia: "ações e execuções de contrato de seguro e de plano de saúde",
    descricao: "Ações e execuções relativas a contratos de seguro (veículo, vida, residencial) e de planos de saúde, incluindo negativa de cobertura.",
    ordem: 3,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "8ª, 9ª e 10ª Cíveis",
    camaras: ["8ª Câmara Cível", "9ª Câmara Cível", "10ª Câmara Cível"],
    secao: "4ª Seção Cível",
    item: "d",
    competencia: "alienação fiduciária e alheios",
    descricao: "Bens em garantia fiduciária e demais casos residuais desta câmara.",
    ordem: 4,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "11ª e 12ª Cíveis",
    camaras: ["11ª Câmara Cível", "12ª Câmara Cível"],
    secao: "5ª Seção Cível",
    item: "a",
    competencia: "Direito de Família, união estável e homoafetiva",
    descricao: "Divórcio, separação, guarda e regulamentação de visitas, pensão alimentícia, união estável e uniões homoafetivas.",
    ordem: 1,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "11ª e 12ª Cíveis",
    camaras: ["11ª Câmara Cível", "12ª Câmara Cível"],
    secao: "5ª Seção Cível",
    item: "b",
    competencia: "ECA, ressalvada a matéria infracional",
    descricao: "Questões cíveis previstas no Estatuto da Criança e do Adolescente, como adoção, guarda e destituição do poder familiar, excluída a matéria infracional.",
    ordem: 2,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "11ª e 12ª Cíveis",
    camaras: ["11ª Câmara Cível", "12ª Câmara Cível"],
    secao: "5ª Seção Cível",
    item: "c",
    competencia: "Direito das Sucessões",
    descricao: "Inventários, arrolamentos, partilhas de bens e demais questões relacionadas à sucessão hereditária.",
    ordem: 3,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "11ª e 12ª Cíveis",
    camaras: ["11ª Câmara Cível", "12ª Câmara Cível"],
    secao: "5ª Seção Cível",
    item: "d",
    competencia: "alienação fiduciária e alheios",
    descricao: "Bens em garantia fiduciária e demais casos residuais desta câmara.",
    ordem: 4,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "13ª, 14ª, 15ª e 16ª Cíveis",
    camaras: ["13ª Câmara Cível", "14ª Câmara Cível", "15ª Câmara Cível", "16ª Câmara Cível"],
    secao: "6ª Seção Cível",
    item: "a",
    competencia: "execuções de título extrajudicial e suas ações, inclusive quando cumuladas com pedido de indenização",
    descricao: "Ações de execução fundadas em títulos extrajudiciais (notas promissórias, cheques, contratos etc.), inclusive quando cumuladas com pedido de indenização.",
    ordem: 1,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "13ª, 14ª, 15ª e 16ª Cíveis",
    camaras: ["13ª Câmara Cível", "14ª Câmara Cível", "15ª Câmara Cível", "16ª Câmara Cível"],
    secao: "6ª Seção Cível",
    item: "b",
    competencia: "negócios jurídicos bancários e cartões de crédito, inclusive quando cumuladas com pedido de indenização, exceto arrendamento mercantil",
    descricao: "Contratos bancários em geral e de cartão de crédito, incluindo revisão de cláusulas e cobrança de dívidas, mesmo quando cumulados com pedido de indenização, exceto arrendamento mercantil.",
    ordem: 2,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "13ª, 14ª, 15ª e 16ª Cíveis",
    camaras: ["13ª Câmara Cível", "14ª Câmara Cível", "15ª Câmara Cível", "16ª Câmara Cível"],
    secao: "6ª Seção Cível",
    item: "c",
    competencia: "alienação fiduciária e alheios",
    descricao: "Bens em garantia fiduciária e demais casos residuais desta câmara.",
    ordem: 3,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "17ª e 18ª Cíveis",
    camaras: ["17ª Câmara Cível", "18ª Câmara Cível"],
    secao: "7ª Seção Cível",
    item: "a",
    competencia: "domínio e posse pura, exceto quando decorrentes de resolução e nulidade de negócios jurídicos",
    descricao: "Ações possessórias (reintegração e manutenção de posse) e de reconhecimento de domínio, exceto quando decorrem de resolução ou nulidade de negócio jurídico.",
    ordem: 1,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "17ª e 18ª Cíveis",
    camaras: ["17ª Câmara Cível", "18ª Câmara Cível"],
    secao: "7ª Seção Cível",
    item: "b",
    competencia: "Direito Falimentar, exceto matéria penal",
    descricao: "Processos de falência e de recuperação judicial e extrajudicial de empresas, exceto os crimes falimentares.",
    ordem: 2,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "17ª e 18ª Cíveis",
    camaras: ["17ª Câmara Cível", "18ª Câmara Cível"],
    secao: "7ª Seção Cível",
    item: "c",
    competencia: "dissolução e liquidação de sociedade",
    descricao: "Ações de dissolução parcial ou total de sociedades empresárias e sua liquidação.",
    ordem: 3,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "17ª e 18ª Cíveis",
    camaras: ["17ª Câmara Cível", "18ª Câmara Cível"],
    secao: "7ª Seção Cível",
    item: "d",
    competencia: "arrendamento mercantil",
    descricao: "Contratos de leasing (arrendamento mercantil) de bens móveis ou imóveis.",
    ordem: 4,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "17ª e 18ª Cíveis",
    camaras: ["17ª Câmara Cível", "18ª Câmara Cível"],
    secao: "7ª Seção Cível",
    item: "e",
    competencia: "contratos de consórcio de bem móvel ou imóvel",
    descricao: "Litígios envolvendo contratos de consórcio para aquisição de bens móveis ou imóveis, como contemplação, atraso na entrega e exclusão de consorciado.",
    ordem: 5,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "17ª e 18ª Cíveis",
    camaras: ["17ª Câmara Cível", "18ª Câmara Cível"],
    secao: "7ª Seção Cível",
    item: "f",
    competencia: "Registros Públicos",
    descricao: "Procedimentos de dúvida e retificação em registros públicos, como registro de imóveis e registro civil.",
    ordem: 6,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "17ª e 18ª Cíveis",
    camaras: ["17ª Câmara Cível", "18ª Câmara Cível"],
    secao: "7ª Seção Cível",
    item: "g",
    competencia: "arrendamento rural, parceria agrícola e empreitada",
    descricao: "Contratos agrários de arrendamento rural e parceria agrícola, além de contratos de empreitada.",
    ordem: 7,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "17ª e 18ª Cíveis",
    camaras: ["17ª Câmara Cível", "18ª Câmara Cível"],
    secao: "7ª Seção Cível",
    item: "h",
    competencia: "locação, inclusive suas execuções",
    descricao: "Contratos de locação residencial e comercial, incluindo ações de despejo, revisional de aluguel e execução de valores locatícios.",
    ordem: 8,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "17ª e 18ª Cíveis",
    camaras: ["17ª Câmara Cível", "18ª Câmara Cível"],
    secao: "7ª Seção Cível",
    item: "i",
    competencia: "alienação fiduciária e alheios",
    descricao: "Bens em garantia fiduciária e demais casos residuais desta câmara.",
    ordem: 9,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "19ª e 20ª Cíveis",
    camaras: ["19ª Câmara Cível", "20ª Câmara Cível"],
    secao: "8ª Seção Cível",
    item: "a",
    competencia: "compromisso e/ou contrato de compra e venda de bens imóveis, sua revisão, resolução, resilição ou rescisão, inclusive referente a vício ou fato do produto, cumulada ou não com responsabilidade indenizatória",
    descricao: "Contratos de compra e venda de imóveis, incluindo revisão, resolução, resilição ou rescisão, e vícios do imóvel (vício redibitório), cumulados ou não com pedido de indenização.",
    ordem: 1,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "19ª e 20ª Cíveis",
    camaras: ["19ª Câmara Cível", "20ª Câmara Cível"],
    secao: "8ª Seção Cível",
    item: "b",
    competencia: "adjudicação compulsória e obrigação de fazer consistente na outorga de escritura pública definitiva, cumulada ou não com indenizatória",
    descricao: "Ações que buscam obrigar o vendedor a outorgar a escritura pública definitiva do imóvel, cumuladas ou não com pedido de indenização.",
    ordem: 2,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "19ª e 20ª Cíveis",
    camaras: ["19ª Câmara Cível", "20ª Câmara Cível"],
    secao: "8ª Seção Cível",
    item: "c",
    competencia: "ação monitória em geral, ressalvada a competência específica das demais câmaras relativamente ao negócio jurídico subjacente",
    descricao: "Ações monitórias para cobrança de dívida com prova escrita sem força executiva, ressalvada a competência específica de outra câmara conforme o negócio jurídico subjacente.",
    ordem: 3,
    fonte: FONTE,
  },
  {
    area: "CIVEL",
    grupo: "19ª e 20ª Cíveis",
    camaras: ["19ª Câmara Cível", "20ª Câmara Cível"],
    secao: "8ª Seção Cível",
    item: "d",
    competencia: "alienação fiduciária e alheios",
    descricao: "Bens em garantia fiduciária e demais casos residuais desta câmara.",
    ordem: 4,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "1ª Criminal",
    camaras: ["1ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "a",
    competencia: "crimes contra a pessoa, exceto os contra a honra",
    descricao: "Homicídio, lesão corporal e demais crimes contra a vida e a integridade física, exceto os crimes contra a honra (calúnia, difamação e injúria).",
    ordem: 1,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "1ª Criminal",
    camaras: ["1ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "b",
    competencia: "crimes militares",
    descricao: "Crimes de natureza militar, praticados por militares ou contra instituições militares.",
    ordem: 2,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "1ª Criminal",
    camaras: ["1ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "c",
    competencia: "processos oriundos do Conselho de Justificação da Polícia Militar",
    descricao: "Processos originados do Conselho de Justificação da Polícia Militar, que apura a incapacidade do militar para permanecer na corporação.",
    ordem: 3,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "2ª Criminal",
    camaras: ["2ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "a",
    competencia: "infrações penais atribuídas a Prefeitos Municipais",
    descricao: "Crimes de responsabilidade e demais infrações penais atribuídas a Prefeitos Municipais no exercício do cargo.",
    ordem: 1,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "2ª Criminal",
    camaras: ["2ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "b",
    competencia: "crimes contra a administração pública",
    descricao: "Corrupção, peculato, prevaricação e demais crimes praticados por funcionários públicos contra a administração.",
    ordem: 2,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "2ª Criminal",
    camaras: ["2ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "c",
    competencia: "crimes contra a fé pública",
    descricao: "Falsificação de documentos públicos ou particulares, moeda falsa e demais crimes que atentam contra a fé pública.",
    ordem: 3,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "2ª Criminal",
    camaras: ["2ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "d",
    competencia: "crimes contra a honra",
    descricao: "Calúnia, difamação e injúria.",
    ordem: 4,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "2ª Criminal",
    camaras: ["2ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "e",
    competencia: "crimes contra a incolumidade pública, incluídos os definidos no Estatuto do Desarmamento",
    descricao: "Crimes que colocam em risco a segurança coletiva, como explosão e incêndio, incluindo os definidos no Estatuto do Desarmamento (posse e porte ilegal de arma de fogo).",
    ordem: 5,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "2ª Criminal",
    camaras: ["2ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "f",
    competencia: "crimes contra a ordem tributária e econômica, contra as relações de consumo e falimentares",
    descricao: "Sonegação fiscal, crimes contra o sistema financeiro e a ordem econômica, crimes contra as relações de consumo e crimes falimentares.",
    ordem: 6,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "2ª Criminal",
    camaras: ["2ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "g",
    competencia: "crimes ambientais",
    descricao: "Crimes praticados contra o meio ambiente, como poluição e desmatamento ilegal.",
    ordem: 7,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "2ª Criminal",
    camaras: ["2ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "h",
    competencia: "demais infrações penais",
    descricao: "Demais infrações penais não atribuídas especificamente a outra câmara criminal.",
    ordem: 8,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "2ª Criminal",
    camaras: ["2ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "i",
    competencia: "atos infracionais previstos no Estatuto da Criança e do Adolescente, por estes praticados",
    descricao: "Atos infracionais (equivalentes a crimes) cometidos por adolescentes, apurados nos termos do Estatuto da Criança e do Adolescente.",
    ordem: 9,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "3ª, 4ª e 5ª Criminais",
    camaras: ["3ª Câmara Criminal", "4ª Câmara Criminal", "5ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "a",
    competencia: "crimes contra o patrimônio",
    descricao: "Furto, roubo, estelionato, apropriação indébita e demais crimes contra o patrimônio.",
    ordem: 1,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "3ª, 4ª e 5ª Criminais",
    camaras: ["3ª Câmara Criminal", "4ª Câmara Criminal", "5ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "b",
    competencia: "crimes contra a dignidade sexual",
    descricao: "Estupro e demais crimes contra a dignidade sexual.",
    ordem: 2,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "3ª, 4ª e 5ª Criminais",
    camaras: ["3ª Câmara Criminal", "4ª Câmara Criminal", "5ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "c",
    competencia: "crimes contra a paz pública",
    descricao: "Crimes contra a paz pública, como associação criminosa e organização criminosa.",
    ordem: 3,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "3ª, 4ª e 5ª Criminais",
    camaras: ["3ª Câmara Criminal", "4ª Câmara Criminal", "5ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "d",
    competencia: "infrações penais relativas a tóxicos e entorpecentes",
    descricao: "Tráfico, posse e demais infrações relacionadas a drogas, previstas na Lei de Drogas.",
    ordem: 4,
    fonte: FONTE,
  },
  {
    area: "CRIMINAL",
    grupo: "3ª, 4ª e 5ª Criminais",
    camaras: ["3ª Câmara Criminal", "4ª Câmara Criminal", "5ª Câmara Criminal"],
    secao: "Seção Criminal",
    item: "e",
    competencia: "demais infrações penais",
    descricao: "Demais infrações penais não atribuídas especificamente a outra câmara criminal.",
    ordem: 5,
    fonte: FONTE,
  },
];
